// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShopASP.Models;

[Table("Order")]
public partial class Order
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [Column("created_at")]
    public DateTime CreatedAt { get; set; }

    [Required]
    [Column("recipient")]
    [StringLength(50)]
    [Unicode(false)]
    public string Recipient { get; set; }

    [Required]
    [Column("country")]
    [StringLength(50)]
    [Unicode(false)]
    public string Country { get; set; }

    [Required]
    [Column("city")]
    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [Column("zip_code")]
    [StringLength(50)]
    [Unicode(false)]
    public string ZipCode { get; set; }

    [Required]
    [Column("street")]
    [StringLength(50)]
    [Unicode(false)]
    public string Street { get; set; }

    [Required]
    [Column("house_number")]
    [StringLength(50)]
    [Unicode(false)]
    public string HouseNumber { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    public virtual User User { get; set; }
}