// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ShopASP.Models;

[Table("User")]
[Index("Id", Name = "IX_User", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("username")]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Required]
    [Column("password_hash")]
    [StringLength(64)]
    [Unicode(false)]
    public string PasswordHash { get; set; }

    [Required]
    [Column("salt")]
    [StringLength(50)]
    [Unicode(false)]
    public string Salt { get; set; }

    [Column("is_admin")]
    public bool IsAdmin { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}